### ISSUE TITLE
check.py is failing

### ISSUE THREAD

**Issue by ValGaOnGitHub** [cubewise-code/tm1py-samples#39]
Installed TM1py and run check.py. It is failing with following:

TM1 User: MyUserID
Password (cmd doesn't show input):
CAM Namespace (leave empty if no CAM Security): devmaple
Address (leave empty if localhost): https://AdminHostName
Port: 13019
SSL (True or False): True
Traceback (most recent call last):
  File "C:\Users\MyUserID\AppData\Local\Programs\Python\Python35\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\MyUserID\AppData\Local\Programs\Python\Python35\lib\site-packages\urllib3\util\connection.py", line 57, in create_connecti
on
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\MyUserID\AppData\Local\Programs\Python\Python35\lib\socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MyUserID\AppData\Local\Programs\Python\Python35\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\MyUserID\AppData\Local\Programs\Python\Python35\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Users\MyUserID\AppData\Local\Programs\Python\Python35\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "C:\Users\MyUserID\AppData\Local\Programs\Python\Python35\lib\site-packages\urllib3\connection.py", line 301, in connect
    conn = self._new_conn()
  File "C:\Users\MyUserID\AppData\Local\Programs\Python\Python35\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x000000000B225358>: Failed to establish a new
connection: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MyUserID\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\MyUserID\AppData\Local\Programs\Python\Python35\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\MyUserID\AppData\Local\Programs\Python\Python35\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //AdminHostName:13019
/api/v1/Configuration/ProductVersion/$value (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000000
B225358>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "check.py", line 20, in <module>
    with TM1Service(address=address, port=port, user=user, password=password, namespace=namespace, ssl=ssl) as tm1:
  File "C:\Users\MyUserID\AppData\Local\Programs\Python\Python35\lib\site-packages\TM1py\Services\TM1Service.py", line 12, in __init__
    self._tm1_rest = RESTService(**kwargs)
  File "C:\Users\MyUserID\AppData\Local\Programs\Python\Python35\lib\site-packages\TM1py\Services\RESTService.py", line 99, in __init__
    self._start_session(**kwargs)
  File "C:\Users\MyUserID\AppData\Local\Programs\Python\Python35\lib\site-packages\TM1py\Services\RESTService.py", line 177, in _start_sess
ion
    response = self.GET(request=request)
  File "C:\Users\MyUserID\AppData\Local\Programs\Python\Python35\lib\site-packages\TM1py\Services\RESTService.py", line 30, in wrapper
    response = func(self, request, data)
  File "C:\Users\MyUserID\AppData\Local\Programs\Python\Python35\lib\site-packages\TM1py\Services\RESTService.py", line 119, in GET
    return self._s.get(url=request, headers=self._headers, data=data, verify=self._verify)
  File "C:\Users\MyUserID\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\MyUserID\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\MyUserID\AppData\Local\Programs\Python\Python35\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)

**Comment by MariusWirtz** [comment]
Assuming that you are running a TM1 version >= 10.2.2 FP 5 this could be three things that are causing this problem:

1. The REST API is not enabled. Check [this article](https://code.cubewise.com/blog/enabling-the-tm1-rest-api)

2. There is a firewall or something else blocking you from contacting the TM1 Server through HTTP. Try to access a simple request against TM1 through your browser, like this one: http://11.27.19.40:9699/api/v1/$metadata
and see if it works

3. Your arguments were incorrect

**Comment by ValGaOnGitHub** [comment]
Must be me. I did it again today and it worked. Thank you for quick response.
