### ISSUE TITLE
'HttpNegotiateAuth' is not defined

### ISSUE THREAD

**Issue by EdouarL** [cubewise-code/tm1py-samples#79]
Hi team, 

I'm trying to test connection. Here my configuration
TM1 and Cognos both on 2 different Windows environment

TM1s.cfg
SecurityPackageName=Kerberos
IntegratedSecurityMode=5
UseSSL=T
HTTPPortNumber=8160
ClientCAMURI=http://sub.domain.com:9300/bi/v1/disp

config.ini
[tm1srv01]
address=localhost
port=8160
user=_myusername_
password=_mypasswordbase64encoded_
ssl=True
decode_b64=True
gateway=http://sub.domain.com:9300/bi/v1/disp
namespace=Cognos Namespace

Here the code with python.exe

from TM1py.Services import TM1Service
import configparser
config = configparser.ConfigParser()
config.read(r'.\config.ini')
with TM1Service(**config['tm1srv01']) as tm1:
    for chore in tm1.chores.get_all():
        chore.reschedule(hours=-1)
        tm1.chores.update(chore)

Traceback (most recent call last):
  File "C:\Users\userBob\AppData\Local\Programs\Python\Python38\lib\site-packages\tm1py-1.5.0-py3.8.egg\TM1py\Services\RestService.py", line 392, in _build_authorization_token_cam
NameError: name 'HttpNegotiateAuth' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\userBob\AppData\Local\Programs\Python\Python38\lib\site-packages\tm1py-1.5.0-py3.8.egg\TM1py\Services\TM1Service.py", line 13, in __init__
  File "C:\Users\userBob\AppData\Local\Programs\Python\Python38\lib\site-packages\tm1py-1.5.0-py3.8.egg\TM1py\Services\RestService.py", line 165, in __init__
  File "C:\Users\userBob\AppData\Local\Programs\Python\Python38\lib\site-packages\tm1py-1.5.0-py3.8.egg\TM1py\Services\RestService.py", line 293, in _start_session
  File "C:\Users\userBob\AppData\Local\Programs\Python\Python38\lib\site-packages\tm1py-1.5.0-py3.8.egg\TM1py\Services\RestService.py", line 383, in _build_authorization_token
  File "C:\Users\userBob\AppData\Local\Programs\Python\Python38\lib\site-packages\tm1py-1.5.0-py3.8.egg\TM1py\Services\RestService.py", line 394, in _build_authorization_token_cam
RuntimeError: SSO failed due to missing dependency requests_negotiate_sspi.HttpNegotiateAuth. SSO only supported for Windows

Could you help ?
many thanks,
Ed

**Comment by MariusWirtz** [comment]
It looks like you are missing a dependency: `requests_negotiate_sspi`.
Just run:
`pip install requests_negotiate_sspi`

By the way, when you authenticate with CAM and SSO, you don't have to provide user and password.

**Comment by EdouarL** [comment]
Right, I incorrect install the requests_negotiate_sspi dependency.
